### ISSUE TITLE
Missing entry in the publication list

### ISSUE THREAD

**Issue by mstalevski** [SKIRT/Web9#2]
Camps & Baes (2018) paper (https://ui.adsabs.harvard.edu/abs/2018ApJ...861...80C/abstract) missing from the publication list at http://www.skirt.ugent.be/root/_publications_all_date.html

**Comment by mbaes** [comment]
This paper does not use SKIRT... we used a light-weight stand-alone 1D Monte Carlo code for this paper.

**Comment by mstalevski** [comment]
Ah, sorry...
